### ISSUE TITLE
사용자 피드백 - infowindow 닫기

### ISSUE THREAD

**Issue by cyberjam** [LifeIsAlone/public-home#12]
사실 마커를 다시 누르면 닫을 수 있는데..

**Comment by ParkAward** [comment]
Info Window가 맵 이동을 진행하면 자동으로 닫아주면 좋겠어요

**Comment by cyberjam** [comment]
사용자 경험이 너무 다양해서 마우스 호버링시 이름만 나타나도록 표시하고 Drawer에 상세 정보 표기하는 것으로 수정 완료
