### ISSUE TITLE
사용자 피드백 - SH 주택목록 추가

### ISSUE THREAD

**Issue by cyberjam** [LifeIsAlone/public-home#13]
기존 LH 매입임대와 SH를 구분하려면 어떻게 할까?

색 구분?

네이버 지도처럼 오른쪽 위 버튼이 있고 필터링?

**Comment by ParkAward** [comment]
마커의 이미지랑 Json에 데이터 형식? 같은걸 더 추가해서 구분하는거죠

**Comment by cyberjam** [comment]
마커 귀엽네요 ㅋㅋㅋ 다만 화면상 LH 글자가 작게 보일 것 같습니다. 
기존에 있던 마커 색깔만 바꿔서 어제 새벽에 잠 안와서 후다닥 했습니다.
