### ISSUE TITLE
구글 자동 번역시 다른 내용으로 바뀌는 경우

### ISSUE THREAD

**Issue by cyberjam** [LifeIsAlone/public-home#18]
![image](https://user-images.githubusercontent.com/20448972/176985740-71e9f08d-b2f4-4e70-b5e6-9fb31adf3bbe.png)

전역적으로 적용하고 싶었는데 잘 적용되지 않아 infowindow만 번역 안되도록 했습니다.
<span class="notranslate">

**Comment by ParkAward** [comment]
확인했습니다

**Comment by cyberjam** [comment]
infowindow 만 번역되지 않도록 조치완료 이슈입니다. 
다른 컨텐츠가 또 있을 경우엔 사이트 전체 번역 안되는 방법을 찾아보도록 하겠습니다.

아래 방법으로 해결 완료. 이슈 종료하겠습니다.
<div className="notranslate"> 대전광역시 어쩌구 저쩌동</div>
