### ISSUE TITLE
coming soon

### ISSUE THREAD

**Issue by cyberjam** [LifeIsAlone/public-home#28]
![20220903_111524](https://user-images.githubusercontent.com/20448972/188259407-6c0c5fc7-6240-4e9e-afaa-6a2f7cb15324.jpg)
벌써 9월이군요

**Comment by ParkAward** [comment]
오늘 하늘보니까 가을이 완연하더라고요. 잘 계시나요~

**Comment by cyberjam** [comment]
그럼요~ 요즘 구해줘 댕냥쓰 프로젝트 맛들어서 조금씩 하다보니 한달 훌쩍 갔네요. Award님은 잘 지내시나요!

**Comment by ParkAward** [comment]
네! 잘지내고 있습니다. 개발을 시작하고 싶은데 계속 더 좋은 코드를 짜야지 하는 욕심 때문에 계속 공부만 하네요..
그래서 시작을 못했네요... 조금씩 짜볼게요 .. 😢

**Comment by cyberjam** [comment]
ㅋㅋㅋㅋ 건강한 욕심입니다. 도약을 위한 웅크림이죠 :) 
마침 저도 공부 겸 다른 프로젝트 수정하고 있었으니 추석 끝나고 함께 밤새어 보아요 😆
