### ISSUE TITLE
Next.js에서 NaverMap loading

### ISSUE THREAD

**Issue by cyberjam** [LifeIsAlone/public-home#29]
- 수정 전 
![image](https://user-images.githubusercontent.com/20448972/189514183-d65d13ec-da36-4177-9834-f32db2f22941.png)

-아래 코드로 수정 후 리로딩할 때만 지도가 정상적으로 로딩
- code 
![image](https://user-images.githubusercontent.com/20448972/189514367-49a0fb61-162f-4d2f-aaaa-e066621f0400.png)

- 새로고침 시 
![image](https://user-images.githubusercontent.com/20448972/189514383-de3a9abe-60e5-4b64-bc30-e0912715cd4e.png)
- 코드 수정으로 인한 자동 리로딩 시
![image](https://user-images.githubusercontent.com/20448972/189514368-ca667876-be8e-4951-9f2d-75509cf696e1.png)

@ParkAward 님 
useEffect 실행 순서가 있는지 지도에 맵이 잘 뜨지 않는군요. 주석에 적으신 이슈가 해당 이슈 맞을까요?

**Comment by ParkAward** [comment]
네 맞습니당

**Comment by cyberjam** [comment]
ㅋㅋㅋㅋㅋ @ParkAward 어디 git 알람갑니까 ㅋㅋㅋㅋ 어째서 칼답이신겁니까
