### ISSUE TITLE
repo 이름에 대문자가 들어갈경우 배포가 되지 않는 이슈

### ISSUE THREAD

**Issue by cyberjam** [LifeIsAlone/public-home#3]
https://cyberjam.github.io/publichome-deploy/
테스트 결과 개인 레포로 fork해서 배포할 경우 흰화면만 나오는 이슈는 동일했고
repo 이름을 소문자로 바꾸니 배포가 되었습니다.
우리 repo도 소문자로 바꿔야 할듯 합니다.

**Comment by ParkAward** [comment]
repo 소문자로 변경하도록 하겠습니다

**Comment by cyberjam** [comment]
감사합니다! 수정 후 우리 repo 배포 잘되는 것 함께 확인하여서 이슈 닫도록 하겠습니다!
