### ISSUE TITLE
NaverMap 관련 Compent 구축

### ISSUE THREAD

**Issue by ParkAward** [LifeIsAlone/public-home#36]
branch: @ParkAward/CustomNaverMap

- [x] NaverMap Test할 방법을 모색한다.
- [x] NaverMap Marker 기능
- [x] NaverMap Marker Info 기능
- [ ] #41
- [ ] NaverMap Marker Center Focus 기능

**Comment by cyberjam** [comment]
Marker Info는 infowindow 말씀 맞을까요? 지금 해보곤 있는데 골머리 아프네요.
Marker Center Focus 는 이전에 panToBounds 맞겠지요?

**Comment by ParkAward** [comment]
네 맞아요. react로 좀 쉽게 구성할 수 있게 만들어 볼게요 기간은 2일 이내에 짜보겠습니다

**Comment by ParkAward** [comment]
@cyberjam  Marker 컴포넌트는 구성했는데요. 아직 infoView 디자인은 만들지는 않았어요
`<Marker>{인포뷰 컴포넌트}</Marekr>`를 넣으면 구현되는 정도에요

혹시 더 원하시는 기능이나, 더 구현해야하는 NaverMap 기능 알려주시면 더 구현해보겠습니다!

저가 개선하고 싶은 방향성이 있는데요. 공유주택 공고 정보를 볼려면 저희가 `마커를 Click`했어야하는데 
Click하면 해당하는 공고의 주소로 이동해서 focus & 정보 를 보여주는건 어떤가요?
벤치마킹: https://hogangnono.com/

이렇게 저희도 재민님이 전처리하신 공고데이터를 Url로 사용자에게 공유할 수 있게 될 수 있도록...

**Comment by cyberjam** [comment]
넵 카카오 react api도 마커 안 children 으로 넣고 있어 사용하기 익숙한 방식입니다. 

좋은 의견 감사합니다. 저도 비슷한 고민을 하고 있었습니다. 마침 인포윈도우를 닫는다는 행위만으로도 사람들이 모두 다양하니까 말이죠. 기존에 마커를 다시 킇릭 하더라도 닫히지만 x를 누르는게 편하다, 이동시 닫히는게 편하다 등등 나뉘는 것처럼요.

이름 같은 최소정보만 인포윈도우나 커스텀 오버레이에 띄워두고 호버링시. 마우스로 가져다 댈때만 나타나도록 하는것도 방법이겠습니다. 누르면 상세 페이지로 이동하구요.

저는 해당 사이트를 참고했으면 합니다. https://xn--ob0ba576m3mgq9a170a.com/Map/location

한편으로는 화면을 이동하는게 맞는건가 싶기도 합니다. 다른 패널을 두고 클릭시 패널에 나타나게 하는것도 방법이긴 한데 핸드폰으로 볼때 영 불편하긴 합니다.

https://saveus.ga/lostMap

일정 화면 크기시 다른 ui로 바꾸거나 닫고 열수 있는 토글을 만드려니 그건 시간이 조금 걸릴것 같구요.

새로운 페이지로 상세페이지 바뀌는게 가장 빠르고 간단하겠습니다!

**Comment by cyberjam** [comment]
상세페이지 새롭게 접속하는 ux로 결정
