### ISSUE TITLE
.Env 요청 입니다.

### ISSUE THREAD

**Issue by ParkAward** [LifeIsAlone/public-home#39]
![image](https://user-images.githubusercontent.com/101157141/190856166-9b6805d8-4f2e-4bd3-a6b2-1496a27f33ad.png)

spreadSheet를 사용하고싶어서요!

**Comment by ParkAward** [comment]
parksangjun1363@gmail.com 에 넣어주세요~

**Comment by cyberjam** [comment]
vercel 배포한다면 github의 secret처럼 env 공유할 수 있을텐데 디코는 길이 제한으로 메일로 드립니다!
a0e4happyhouse@gmail.com 입니다
