### ISSUE TITLE
Vercel team 권한 요청

### ISSUE THREAD

**Issue by cyberjam** [LifeIsAlone/public-home#42]
![image](https://user-images.githubusercontent.com/20448972/190890319-be42d257-0981-4d54-9045-eccaf967e6a3.png)

@ParkAward 
vercel lifeisalone team에 request 했습니다. 시간나실때 accept 해주세용
https://vercel.com/account/teams

**Comment by ParkAward** [comment]
![image](https://user-images.githubusercontent.com/101157141/190890853-b18bcb3e-7a46-4e63-8f48-04891f0c5c62.png)

**Comment by cyberjam** [comment]
공용깃계정으로 배포 중

**Comment by cyberjam** [comment]
공용 깃 계정, pw 디코로 공유 완료 
a0e4happyhouse@gmail.com

배포 페이지 
https://public-home.vercel.app/

**Comment by cyberjam** [comment]
공용 깃 계정, pw 디코로 공유 완료
[a0e4happyhouse@gmail.com](mailto:a0e4happyhouse@gmail.com)

배포 페이지
https://public-home.vercel.app/
