### ISSUE TITLE
UI/UX 업데이트 계획

### ISSUE THREAD

**Issue by ParkAward** [LifeIsAlone/public-home#45]
branch: @parkaward/impoveUI
 
일정 : 10/02 ~

- [ ] :UI 개선하기 🏃‍♂️

**Comment by cyberjam** [comment]
@ParkAward 님 10월 2일 부터는 기간이 많이 늦습니다.

**Comment by ParkAward** [comment]
@cyberjam UI 이전 이랑 똑같이 복구할까요? 금방 할 것 같은데요

**Comment by cyberjam** [comment]
@ParkAward 기간이 늦으니 예전 UI로 복구한다는 말씀이실까요? 
이미 Drawer 작업하셨으니 바쁘시다면 관련 UI 제가 손보도록 하겠습니다. 관련 PR https://github.com/LifeIsAlone/public-home/pull/47 https://github.com/LifeIsAlone/public-home/pull/46 확인해보시고 accept만 처리해주시면 좋겠습니다.
검색기능은 바쁘시다면 이번엔 삭제하여 사용자에게 배포하도록 하겠습니다.
