### ISSUE TITLE
Drawer UI

### ISSUE THREAD

**Issue by cyberjam** [LifeIsAlone/public-home#49]
- [x] 최대전환시 문구 삽입
- [x] Drawer가 marker클릭시 열리도록 
- [x] Drawer toggle image - naver map
- [x] Drawer 에 승강기, 층수, 방수 만 추가적으로 표시 (minor)
- [ ] Drawer sells가 카드 처럼. - 구해줘 댕냥쓰 Aside(Drawer)참고
- [x] Drawer scroll
- [x] 아래 ; 제거

**Comment by ParkAward** [comment]
....
